name: Deploy to Digital Ocean

on:
  push:
    branches: [main, auto-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build --workspace=frontend

      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/dist/*"
          target: "/var/www/journal-app/"
          script: |
            cd /home/deploy/journal-organizer
            git pull origin main
            npm install
            cd backend && npm install
            pm2 restart journal-backend || pm2 start server.js --name journal-backend
            sudo systemctl reload nginx
